name: Clang Tidy

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Install MetaCall language dependencies
        run: |
          ./tools/metacall-environment.sh \
          debug \
          python \
          ruby \
          nodejs \
          typescript \
          file \
          rpc \
          wasm \
          java \
          c \
          cobol \
          rust
      - name: Configure MetaCall
        run: |
          mkdir -p build
          cd build
          ../tools/metacall-configure.sh \
          debug \
          python \
          ruby \
          nodejs \
          typescript \
          file \
          rpc \
          wasm \
          java \
          c \
          cobol \
          rust

      - name: Run clang-tidy
        run: cmake --build build --target clang-tidy

  clang-tidy-windows-test:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install clang-tidy
        shell: pwsh
        run: .\tools\metacall-environment.ps1 clangtidy

      - name: Verify clang-tidy
        shell: pwsh
        run: |
          Get-Command clang-tidy
          clang-tidy --version

  clang-tidy-macos:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install clang-tidy
        run: ./tools/metacall-environment.sh debug clangtidy

      - name: Verify clang-tidy
        run: |
          which clang-tidy
          clang-tidy --version